export const Productconst = {
    GETPRODUCT_REQUEST: "GETPRODUCT_REQUEST",
    GETPRODUCT_SUCESS: "GETPRODUCT_SUCESS",
    GETDROPPRODUCT_VALUE: "GETDROPPRODUCT_VALUE",
    GETDROPSTATE_VALUE: "GETDROPSTATE_VALUE",
    GETDROPCITY_VALUE: "GETDROPCITY_VALUE",


}